# Generated by Django 3.0.2 on 2020-02-09 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 11, 7, 37, 805162)),
        ),
    ]
