# Generated by Django 3.0.2 on 2020-01-31 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='portfolio_balance',
        ),
    ]
