# Generated by Django 3.0.2 on 2020-01-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bitcoin_price',
            field=models.DecimalField(decimal_places=2, default=9330.95744943, max_digits=12),
        ),
    ]
