# Generated by Django 3.0.2 on 2020-02-08 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 16, 21, 15, 898403)),
        ),
    ]
