# Generated by Django 3.0.2 on 2020-02-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200207_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account_transactions',
            new_name='user',
        ),
    ]
