# Generated by Django 3.0.2 on 2020-01-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200128_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bitcoin_price',
            field=models.DecimalField(decimal_places=2, default=9329.06871771, max_digits=12),
        ),
    ]
