# Generated by Django 3.0.2 on 2020-01-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_account_bitcoin_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=12),
        ),
    ]
