# Generated by Django 3.0.2 on 2020-02-08 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200208_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 16, 22, 44, 428962)),
        ),
    ]
