# Generated by Django 3.0.2 on 2020-01-26 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_todolist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
