# Generated by Django 3.0.2 on 2020-02-08 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200208_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='transaction_total_usd_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 17, 7, 58, 855609)),
        ),
    ]
