# Generated by Django 3.0.2 on 2020-01-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200128_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bitcoin_price',
        ),
    ]
