# Generated by Django 3.0.2 on 2020-01-30 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_account_bitcoin_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='portfolio_balance',
        ),
    ]
